// <auto-generated />
using EFCoreWebDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MoreVideotapesGalore.Migrations
{
    [DbContext(typeof(VideoTapeContext))]
    [Migration("20181019175511_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoreVideotapesGalore.Models.Entities.Borrow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("borrow_date");

                    b.Property<string>("return_date");

                    b.HasKey("id");

                    b.ToTable("Borrows");
                });

            modelBuilder.Entity("MoreVideotapesGalore.Models.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<string>("email");

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.Property<string>("phone_number");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoreVideotapesGalore.Models.Entities.Videotape", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("director_name");

                    b.Property<string>("eidr");

                    b.Property<string>("release_date");

                    b.Property<string>("type");

                    b.HasKey("id");

                    b.ToTable("Videotapes");
                });
#pragma warning restore 612, 618
        }
    }
}
